# hardcoded-credentials.yml
#
# what:
# github actions supports running jobs within containers, as well as spawning
# adjacent containerized services. in both cases, github actions also supports
# referencing a remote container image on a registry, along with credentials
# for authenticating to that registry. a user may accidentally disclose
# sensitive (e.g. overscoped) registry credentials by hardcoding them
# rather than accessing them via the `secrets` context.
#
# how:
# user error.
#
# see also: https://github.com/rhysd/actionlint/blob/main/docs/checks.md#hardcoded-credentials

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: fake.example.com/example
      credentials:
        username: user
        # NOT OK: hardcoded credential
        password: hackme
    services:
      service-1:
        image: fake.example.com/anotherexample
        credentials:
          username: user
          # NOT OK: hardcoded credential
          password: hackme
      service-2:
        image: fake.example.com/yetanotherexample
        credentials:
          username: user
          # OK: not hardcoded
          password: ${{ secrets.SOME_SECRET }}
    steps:
      - run: echo 'vulnerable!'
